site_name: VS Code Docs
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Nunito
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

nav:
  - Home: "index.md"
  - Configure GitHub repositories: "github_repo.md"
  - Install, activate, and deactivate third-party extensions: "extensions.md"
  - Customize keyboard shortcuts: "keyboard_shortcuts.md"
  - Troubleshooting: "Troubleshooting.md"
  - Glossary: "Glossary.md"
